name: User Pull Request

on:
  pull_request:
    branches: [ "main" ]

jobs:
  thank_user:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Post Thank You Message
      uses: actions/github-script@v6
      env:
          GITHUB_TOKEN: ${{ secrets.MY_PAT }}
      with:
        script: |
          const actor = context.actor;
          const prNumber = context.payload.pull_request.number;
          github.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: prNumber,
            body: `Terima kasih, @${actor}, atas kontribusi anda🥳! Kami sangat menghargai upaya Anda.`
          });
